export type Language = 'javascript' | 'typescript' | 'python';

export type ReviewType = 'monaco' | 'upload';

export type Severity = 'critical' | 'warning' | 'info';

export type Verdict = 'CORRECT' | 'INCORRECT';

export type FindingCategory =
  | 'bug'
  | 'security'
  | 'smell'
  | 'performance'
  | 'naming'
  | 'best_practice'
  | 'refactor'
  | 'static';

export interface Profile {
  id: string;
  name: string;
  avatar_url: string | null;
  updated_at: string;
}

export interface Project {
  id: string;
  user_id: string;
  name: string;
  description: string | null;
  language: Language;
  created_at: string;
}

export interface StaticFinding {
  rule: string;
  severity: Severity;
  message: string;
  line: number;
  column: number;
  category: FindingCategory;
}

export interface AIFinding {
  issue: string;
  explanation: string;
  suggested_fix: string;
  line_number?: number;
}

export interface AIFindings {
  bug_detection: AIFinding[];
  security_issues: AIFinding[];
  code_smells: AIFinding[];
  performance_suggestions: AIFinding[];
  naming_suggestions: AIFinding[];
  best_practices: AIFinding[];
  refactoring_suggestions: AIFinding[];
}

export interface ComplexityMetrics {
  cyclomatic_complexity: number;
  function_complexity: number;
  file_complexity: number;
  number_of_functions: number;
  number_of_classes: number;
  lines_of_code: number;
  maintainability_index: number;
  per_function: { name: string; complexity: number; lines: number }[];
}

export interface ReviewFinding {
  id: string;
  review_id: string;
  severity: Severity;
  category: FindingCategory;
  issue: string;
  explanation: string;
  suggested_fix: string;
  file_name: string;
  line_number: number;
}

/** A single test case generated by the AI reviewer */
export interface TestCase {
  description: string;
  input: string;
  expected: string;
  actual: string;
  passes: boolean;
}

export interface Review {
  id: string;
  project_id: string;
  user_id: string;
  review_type: ReviewType;
  language: Language;
  file_name: string;
  source_code: string;
  overall_score: number;
  summary: string;
  plain_english: string;
  documentation: string;
  complexity: ComplexityMetrics;
  static_findings: StaticFinding[];
  ai_findings: AIFindings;
  status: 'completed' | 'failed';
  created_at: string;
  // --- 5-step pipeline fields ---
  verdict: Verdict;
  confidence: number;           // 0–100
  intent: string;               // inferred purpose
  assumptions: string;          // assumptions made during analysis
  deep_analysis: string;        // full STEP 1–5 narrative
  suggested_fix: string;        // corrected code
  test_cases: TestCase[];       // generated test cases
}

export interface ReviewWithProject extends Review {
  project?: Pick<Project, 'id' | 'name'>;
}

export interface AIReviewResponse {
  overall_score: number;
  executive_summary: string;
  plain_english: string;
  documentation: string;
  findings: AIFindings;
  // --- 5-step pipeline fields ---
  verdict: Verdict;
  confidence: number;
  intent: string;
  assumptions: string;
  deep_analysis: string;
  suggested_fix: string;
  test_cases: TestCase[];
}
